import { QueryDeclaration, TransactionDeclaration, TypeRef } from "./ast.js";
import { parseProgram } from "./parser.js";
import { queryToPostgres, transactionToPostgres } from "./postgres.js";
import { buildSchema, FieldIr, findEntity, SchemaIr } from "./schema.js";

export interface TypeScriptApiOptions {
  runtimeImport?: string;
}

export function emitTypeScriptApi(source: string, options: TypeScriptApiOptions = {}): string {
  const program = parseProgram(source);
  const schema = buildSchema(program);
  const queries = program.declarations.filter((declaration): declaration is QueryDeclaration => declaration.kind === "query");
  const transactions = program.declarations.filter(
    (declaration): declaration is TransactionDeclaration => declaration.kind === "transaction",
  );
  const apiName = `${pascalCase(program.moduleName)}Api`;
  const createName = `create${apiName}`;
  const runtimeImport = options.runtimeImport ?? "./runtime.js";

  const lines = [
    "// Generated by Reux. Do not edit by hand.",
    `import type { Database, QueryRunResult, TransactionRunResult } from ${quoteString(runtimeImport)};`,
    `import { runSqlQuery, runTransactionSql } from ${quoteString(runtimeImport)};`,
    "",
    "export type ReuxQueryResult<T> = QueryRunResult & { rows: T[] };",
    "",
    ...enumTypes(schema),
    ...entityTypes(schema),
    ...queryTypes(schema, queries),
    ...transactionTypes(transactions, schema),
    ...apiInterface(apiName, queries, transactions),
    ...sqlConstants(schema, queries, transactions),
    ...apiFactory(createName, apiName, queries, transactions),
  ];

  return `${lines.join("\n")}\n`;
}

function enumTypes(schema: SchemaIr): string[] {
  return schema.enums.flatMap((enumeration) => [
    `export type ${enumeration.name} = ${enumeration.values.map((value) => quoteString(value)).join(" | ")};`,
    "",
  ]);
}

function entityTypes(schema: SchemaIr): string[] {
  return schema.entities.flatMap((entity) => [
    `export interface ${entity.name}Row {`,
    ...entity.fields.map((field) => `  ${field.columnName}${field.nullable ? "?" : ""}: ${fieldType(schema, field)};`),
    "}",
    "",
  ]);
}

function queryTypes(schema: SchemaIr, queries: QueryDeclaration[]): string[] {
  return queries.flatMap((query) => [
    ...parameterInterface(schema, `${pascalCase(query.name)}Params`, query.parameters),
    `export type ${pascalCase(query.name)}Row = ${queryRowType(schema, query)};`,
    "",
  ]);
}

function transactionTypes(transactions: TransactionDeclaration[], schema?: SchemaIr): string[] {
  return transactions.flatMap((transaction) => parameterInterface(schema, `${pascalCase(transaction.name)}Params`, transaction.parameters));
}

function parameterInterface(schema: SchemaIr | undefined, name: string, parameters: { name: string; type: TypeRef }[]): string[] {
  if (parameters.length === 0) return [];
  return [
    `export interface ${name} {`,
    ...parameters.map((parameter) => `  ${parameter.name}${parameter.type.optional ? "?" : ""}: ${typeRefToTs(parameter.type, schema)};`),
    "}",
    "",
  ];
}

function apiInterface(apiName: string, queries: QueryDeclaration[], transactions: TransactionDeclaration[]): string[] {
  return [
    `export interface ${apiName} {`,
    "  queries: {",
    ...queries.map(
      (query) =>
        `    ${query.name}(${parameterSignature(query.name, query.parameters)}): Promise<ReuxQueryResult<${pascalCase(query.name)}Row>>;`,
    ),
    "  };",
    "  transactions: {",
    ...transactions.map(
      (transaction) =>
        `    ${transaction.name}(${parameterSignature(transaction.name, transaction.parameters)}): Promise<TransactionRunResult>;`,
    ),
    "  };",
    "}",
    "",
  ];
}

function sqlConstants(schema: SchemaIr, queries: QueryDeclaration[], transactions: TransactionDeclaration[]): string[] {
  return [
    "const querySql = {",
    ...queries.map((query) => `  ${query.name}: ${templateString(queryToPostgres(schema, query))},`),
    "} as const;",
    "",
    "const transactionSql = {",
    ...transactions.map((transaction) => `  ${transaction.name}: ${templateString(transactionToPostgres(schema, transaction))},`),
    "} as const;",
    "",
  ];
}

function apiFactory(
  createName: string,
  apiName: string,
  queries: QueryDeclaration[],
  transactions: TransactionDeclaration[],
): string[] {
  return [
    `export function ${createName}(db: Database): ${apiName} {`,
    "  return {",
    "    queries: {",
    ...queries.map((query) => queryFactoryMethod(query)),
    "    },",
    "    transactions: {",
    ...transactions.map((transaction) => transactionFactoryMethod(transaction)),
    "    },",
    "  };",
    "}",
    "",
  ];
}

function queryFactoryMethod(query: QueryDeclaration): string {
  const params = orderedParams(query.parameters);
  const args = query.parameters.length > 0 ? `params: ${pascalCase(query.name)}Params` : "";
  return [
    `      async ${query.name}(${args}) {`,
    `        return runSqlQuery(db, querySql.${query.name}, ${params}) as Promise<ReuxQueryResult<${pascalCase(query.name)}Row>>;`,
    "      },",
  ].join("\n");
}

function transactionFactoryMethod(transaction: TransactionDeclaration): string {
  const params = orderedParams(transaction.parameters);
  const args = transaction.parameters.length > 0 ? `params: ${pascalCase(transaction.name)}Params` : "";
  const attempts = transaction.retry?.attempts ?? 1;
  return [
    `      async ${transaction.name}(${args}) {`,
    `        return runTransactionSql(db, transactionSql.${transaction.name}, ${params}, ${attempts});`,
    "      },",
  ].join("\n");
}

function orderedParams(parameters: { name: string }[]): string {
  if (parameters.length === 0) return "[]";
  return `[${parameters.map((parameter) => `params.${parameter.name}`).join(", ")}]`;
}

function parameterSignature(name: string, parameters: { name: string; type: TypeRef }[]): string {
  return parameters.length === 0 ? "" : `params: ${pascalCase(name)}Params`;
}

function queryRowType(schema: SchemaIr, query: QueryDeclaration): string {
  const record = parseQueryRecord(query.resultType);
  if (record) {
    return `{ ${[...record.entries()].map(([name, type]) => `${name}: ${sourceTypeToTs(schema, type)}`).join("; ")} }`;
  }

  const entityMatch = query.resultType.match(/^Query<([A-Za-z_][A-Za-z0-9_]*)>$/);
  const entity = entityMatch ? findEntity(schema, entityMatch[1]) : undefined;
  return entity ? `${entity.name}Row` : "unknown";
}

function parseQueryRecord(resultType: string): Map<string, string> | undefined {
  const match = resultType.match(/^Query<\{(.+)\}>$/);
  if (!match) return undefined;
  const fields = new Map<string, string>();
  for (const part of splitTopLevel(match[1], ",")) {
    const separator = part.indexOf(":");
    if (separator < 0) return undefined;
    fields.set(part.slice(0, separator).trim(), part.slice(separator + 1).trim());
  }
  return fields;
}

function splitTopLevel(source: string, separator: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;
  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    if (char === "<" || char === "{" || char === "(") depth += 1;
    if (char === ">" || char === "}" || char === ")") depth -= 1;
    if (depth === 0 && char === separator) {
      parts.push(source.slice(start, index).trim());
      start = index + 1;
    }
  }
  parts.push(source.slice(start).trim());
  return parts.filter(Boolean);
}

function fieldType(schema: SchemaIr, field: FieldIr): string {
  const value = field.reference ? "string" : sourceTypeNameToTs(field.type.name, field.type.args[0]?.name, schema);
  return field.nullable ? `${value} | null` : value;
}

function typeRefToTs(type: TypeRef, schema?: SchemaIr): string {
  const base = sourceTypeNameToTs(type.name, type.args[0]?.name, schema);
  return type.optional ? `${base} | null` : base;
}

function sourceTypeToTs(schema: SchemaIr, source: string): string {
  const trimmed = source.trim();
  const optional = trimmed.endsWith("?");
  const required = optional ? trimmed.slice(0, -1) : trimmed;
  const idMatch = required.match(/^Id<([A-Za-z_][A-Za-z0-9_]*)>$/);
  const base = idMatch ? "string" : sourceTypeNameToTs(required, undefined, schema);
  return optional ? `${base} | null` : base;
}

function sourceTypeNameToTs(typeName: string, idArg?: string, schema?: SchemaIr): string {
  if (typeName === "Id" || idArg) return "string";
  if (schema?.enums.some((enumeration) => enumeration.name === typeName)) return typeName;
  if (schema?.entities.some((entity) => entity.name === typeName)) return "string";
  switch (typeName) {
    case "Bool":
      return "boolean";
    case "Int":
      return "number";
    case "Int64":
      return "number | string";
    case "Float":
    case "Decimal":
      return "number | string";
    case "String":
    case "Bytes":
    case "Duration":
    case "Uuid":
      return "string";
    case "Date":
    case "Time":
    case "Instant":
      return "string | Date";
    case "Json":
      return "unknown";
    default:
      return typeName;
  }
}

function pascalCase(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9]+/g, " ");
  const words = cleaned.match(/[A-Za-z0-9]+/g) ?? ["Reux"];
  return words.map((word) => `${word[0].toUpperCase()}${word.slice(1)}`).join("");
}

function quoteString(value: string): string {
  return JSON.stringify(value);
}

function templateString(value: string): string {
  return `\`${value.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${")}\``;
}
