import { QueryDeclaration, TransactionDeclaration, TypeRef } from "./ast.js";
import { parseProgram, parseTypeRef } from "./parser.js";
import { queryToPostgres, transactionToPostgres } from "./postgres.js";
import { inferQueryResultType } from "./query-ir.js";
import { buildSchema, FieldIr, findEntity, SchemaIr } from "./schema.js";

export interface TypeScriptApiOptions {
  runtimeImport?: string;
}

export interface TypeScriptApiServerOptions {
  apiImport?: string;
  configImport?: string;
  runtimeImport?: string;
}

export interface TypeScriptWorkerOptions {
  configImport?: string;
  runtimeImport?: string;
}

export function emitTypeScriptApi(source: string, options: TypeScriptApiOptions = {}): string {
  const program = parseProgram(source);
  const schema = buildSchema(program);
  const queries = program.declarations.filter((declaration): declaration is QueryDeclaration => declaration.kind === "query");
  const transactions = program.declarations.filter(
    (declaration): declaration is TransactionDeclaration => declaration.kind === "transaction",
  );
  const apiName = `${pascalCase(program.moduleName)}Api`;
  const createName = `create${apiName}`;
  const runtimeImport = options.runtimeImport ?? "./runtime.js";

  const lines = [
    "// Generated by Reux. Do not edit by hand.",
    `import type { Database, QueryRunResult, TransactionRunResult } from ${quoteString(runtimeImport)};`,
    `import { runSqlQuery, runTransactionSql } from ${quoteString(runtimeImport)};`,
    "",
    "export type ReuxQueryResult<T> = QueryRunResult & { rows: T[] };",
    "",
    ...enumTypes(schema),
    ...entityTypes(schema),
    ...queryTypes(schema, queries),
    ...transactionTypes(transactions, schema),
    ...apiInterface(apiName, queries, transactions),
    ...sqlConstants(schema, queries, transactions),
    ...apiFactory(createName, apiName, queries, transactions),
  ];

  return `${lines.join("\n")}\n`;
}

export function emitTypeScriptApiServer(source: string, options: TypeScriptApiServerOptions = {}): string {
  const program = parseProgram(source);
  const schema = buildSchema(program);
  const queries = program.declarations.filter((declaration): declaration is QueryDeclaration => declaration.kind === "query");
  const transactions = program.declarations.filter(
    (declaration): declaration is TransactionDeclaration => declaration.kind === "transaction",
  );
  const apiName = `${pascalCase(program.moduleName)}Api`;
  const createName = `create${apiName}`;
  const apiImport = options.apiImport ?? "./api.js";
  const configImport = options.configImport ?? "./config.js";
  const runtimeImport = options.runtimeImport ?? "./runtime.js";
  const typeNames = [
    ...queries.filter((query) => query.parameters.length > 0).map((query) => `${pascalCase(query.name)}Params`),
    ...transactions
      .filter((transaction) => transaction.parameters.length > 0)
      .map((transaction) => `${pascalCase(transaction.name)}Params`),
  ];
  const apiNamedImports = [createName];

  const lines = [
    "// Generated by Reux. Do not edit by hand.",
    'import { createServer, type IncomingMessage, type ServerResponse } from "node:http";',
    `import { loadConfig } from ${quoteString(configImport)};`,
    `import { createPostgresDatabase } from ${quoteString(runtimeImport)};`,
    `import { ${apiNamedImports.join(", ")}${typeNames.length > 0 ? `, type ${typeNames.join(", type ")}` : ""} } from ${quoteString(apiImport)};`,
    "",
    "const db = createPostgresDatabase(loadConfig());",
    `const api = ${createName}(db);`,
    "const port = Number.parseInt(process.env.PORT ?? \"3000\", 10);",
    "const maxBodyBytes = Number.parseInt(process.env.REUX_HTTP_MAX_BODY_BYTES ?? \"1048576\", 10);",
    "",
    "const routes = {",
    "  queries: {",
    ...queries.map((query) => routeHandler("queries", query.name, query.parameters.length > 0 ? `${pascalCase(query.name)}Params` : undefined)),
    "  },",
    "  transactions: {",
    ...transactions.map((transaction) =>
      routeHandler("transactions", transaction.name, transaction.parameters.length > 0 ? `${pascalCase(transaction.name)}Params` : undefined),
    ),
    "  },",
    "} as const;",
    "",
    "type ExpectedParam = { name: string; optional: boolean; kind: \"boolean\" | \"integer\" | \"number\" | \"numeric\" | \"string\" | \"json\" };",
    "",
    "const routeParams = {",
    "  queries: {",
    ...queries.map((query) => routeParamSpec(schema, query.name, query.parameters)),
    "  },",
    "  transactions: {",
    ...transactions.map((transaction) => routeParamSpec(schema, transaction.name, transaction.parameters)),
    "  },",
    "} as const;",
    "",
    "const server = createServer(async (request, response) => {",
    "  try {",
    "    await handleRequest(request, response);",
    "  } catch (error) {",
    "    sendJson(response, 500, { error: error instanceof Error ? error.message : String(error) });",
    "  }",
    "});",
    "",
    "server.listen(port, () => {",
    '  console.log(`Reux API server listening on http://127.0.0.1:${port}`);',
    "});",
    "",
    "async function handleRequest(request: IncomingMessage, response: ServerResponse): Promise<void> {",
    "  const method = request.method ?? \"GET\";",
    "  const url = new URL(request.url ?? \"/\", \"http://127.0.0.1\");",
    "",
    "  if (method === \"GET\" && url.pathname === \"/health\") {",
    `    sendJson(response, 200, { ok: true, module: ${quoteString(program.moduleName)} });`,
    "    return;",
    "  }",
    "",
    "  if (method !== \"POST\") {",
    "    sendJson(response, 405, { error: \"method not allowed\" });",
    "    return;",
    "  }",
    "",
    "  const [, group, name] = url.pathname.split(\"/\");",
    "  if (!isRouteGroup(group) || !name || !(name in routes[group])) {",
    "    sendJson(response, 404, { error: \"route not found\" });",
    "    return;",
    "  }",
    "",
    "  const body = await readJson(request, response);",
    "  if (body === undefined) return;",
    "  const expectedParams = routeParams[group][name as keyof (typeof routeParams)[typeof group]] as readonly ExpectedParam[];",
    "  const validationError = validateBody(body, expectedParams);",
    "  if (validationError) {",
    "    sendJson(response, 400, { error: validationError });",
    "    return;",
    "  }",
    "  const handler = routes[group][name as keyof (typeof routes)[typeof group]] as (body: unknown) => Promise<unknown>;",
    "  sendJson(response, 200, await handler(body));",
    "}",
    "",
    "function isRouteGroup(value: string | undefined): value is keyof typeof routes {",
    "  return value === \"queries\" || value === \"transactions\";",
    "}",
    "",
    "function readJson(request: IncomingMessage, response: ServerResponse): Promise<unknown | undefined> {",
    "  return new Promise((resolve, reject) => {",
    "    let body = \"\";",
    "    let tooLarge = false;",
    "    request.setEncoding(\"utf8\");",
    "    request.on(\"data\", (chunk) => {",
    "      if (tooLarge) return;",
    "      body += chunk;",
    "      if (Buffer.byteLength(body, \"utf8\") > maxBodyBytes) {",
    "        tooLarge = true;",
    "        sendJson(response, 413, { error: \"request body too large\" });",
    "        request.destroy();",
    "        resolve(undefined);",
    "      }",
    "    });",
    "    request.on(\"end\", () => {",
    "      if (tooLarge) return;",
    "      if (!body.trim()) {",
    "        resolve({});",
    "        return;",
    "      }",
    "      try {",
    "        resolve(JSON.parse(body) as unknown);",
    "      } catch (error) {",
    "        sendJson(response, 400, { error: \"invalid JSON request body\" });",
    "        resolve(undefined);",
    "      }",
    "    });",
    "    request.on(\"error\", reject);",
    "  });",
    "}",
    "",
    "function validateBody(body: unknown, expectedParams: readonly ExpectedParam[]): string | undefined {",
    "  if (!isPlainObject(body)) return \"request body must be a JSON object\";",
    "  const expectedNames = new Set(expectedParams.map((parameter) => parameter.name));",
    "  for (const key of Object.keys(body)) {",
    "    if (!expectedNames.has(key)) return `unknown parameter: ${key}`;",
    "  }",
    "  for (const parameter of expectedParams) {",
    "    if (!parameter.optional && !(parameter.name in body)) return `missing required parameter: ${parameter.name}`;",
    "    if (!(parameter.name in body)) continue;",
    "    const value = body[parameter.name];",
    "    if (parameter.optional && value === null) continue;",
    "    const typeError = validateParamValue(value, parameter);",
    "    if (typeError) return typeError;",
    "  }",
    "  return undefined;",
    "}",
    "",
    "function validateParamValue(value: unknown, parameter: ExpectedParam): string | undefined {",
    "  const valid =",
    "    parameter.kind === \"boolean\" ? typeof value === \"boolean\" :",
    "    parameter.kind === \"integer\" ? typeof value === \"number\" && Number.isInteger(value) :",
    "    parameter.kind === \"number\" ? typeof value === \"number\" && Number.isFinite(value) :",
    "    parameter.kind === \"numeric\" ? (typeof value === \"number\" && Number.isFinite(value)) || (typeof value === \"string\" && value.trim().length > 0) :",
    "    parameter.kind === \"string\" ? typeof value === \"string\" :",
    "    true;",
    "  return valid ? undefined : `${parameter.name} must be ${paramKindDescription(parameter.kind)}`;",
    "}",
    "",
    "function paramKindDescription(kind: ExpectedParam[\"kind\"]): string {",
    "  switch (kind) {",
    "    case \"boolean\": return \"a boolean\";",
    "    case \"integer\": return \"an integer number\";",
    "    case \"number\": return \"a finite number\";",
    "    case \"numeric\": return \"a finite number or numeric string\";",
    "    case \"string\": return \"a string\";",
    "    case \"json\": return \"valid JSON\";",
    "  }",
    "}",
    "",
    "function isPlainObject(value: unknown): value is Record<string, unknown> {",
    "  return typeof value === \"object\" && value !== null && !Array.isArray(value);",
    "}",
    "",
    "function sendJson(response: ServerResponse, statusCode: number, body: unknown): void {",
    "  response.writeHead(statusCode, { \"content-type\": \"application/json\" });",
    "  response.end(`${JSON.stringify(body, null, 2)}\\n`);",
    "}",
  ];

  return `${lines.join("\n")}\n`;
}

export function emitTypeScriptWorker(source: string, options: TypeScriptWorkerOptions = {}): string {
  const program = parseProgram(source);
  const schema = buildSchema(program);
  const transactions = program.declarations.filter(
    (declaration): declaration is TransactionDeclaration => declaration.kind === "transaction",
  );
  const events = unique(transactions.flatMap((transaction) => enqueueEvents(transaction.body)));
  const hooks = unique(transactions.flatMap((transaction) => afterCommitHooks(transaction.body)));
  const configImport = options.configImport ?? "./config.js";
  const runtimeImport = options.runtimeImport ?? "./runtime.js";

  const lines = [
    "// Generated by Reux. Fill in handlers before running in production.",
    `import { loadConfig } from ${quoteString(configImport)};`,
    `import { createPostgresDatabase, runOutboxWorker, type AfterCommitHandler, type OutboxHandler, type AfterCommitHook, type OutboxEvent } from ${quoteString(runtimeImport)};`,
    "",
    ...eventPayloadTypes(schema),
    ...hookTypes(hooks),
    "type TypedOutboxHandler<T> = (event: OutboxEvent & { payload: T }) => Promise<void> | void;",
    "",
    "const db = createPostgresDatabase(loadConfig());",
    "const controller = new AbortController();",
    "const intervalMs = Number.parseInt(process.env.REUX_WORKER_INTERVAL_MS ?? \"1000\", 10);",
    "const limit = Number.parseInt(process.env.REUX_WORKER_LIMIT ?? \"10\", 10);",
    "const maxAttempts = Number.parseInt(process.env.REUX_WORKER_MAX_ATTEMPTS ?? \"5\", 10);",
    "const retryDelaySeconds = Number.parseInt(process.env.REUX_WORKER_RETRY_DELAY_SECONDS ?? \"30\", 10);",
    "const requeueStaleAfterSeconds = Number.parseInt(process.env.REUX_WORKER_REQUEUE_STALE_SECONDS ?? \"300\", 10);",
    "",
    outboxHandlerDeclaration(events, schema),
    ...(events.length > 0
      ? events.map((event) => `  ${event}: async (event) => {\n    console.log("outbox event", event.eventType, event.id, event.payload);\n  },`)
      : ["  // No enqueue statements were found in this Reux source."]),
    "};",
    "",
    afterCommitHandlerDeclaration(hooks),
    ...(hooks.length > 0
      ? hooks.map((hook) => `  ${hook}: async (hook) => {\n    console.log("after commit hook", hook.call, hook.resolvedArgs ?? hook.args);\n  },`)
      : ["  // No after commit hooks were found in this Reux source."]),
    "};",
    "",
    "for (const signal of [\"SIGINT\", \"SIGTERM\"] as const) {",
    "  process.once(signal, () => controller.abort());",
    "}",
    "",
    "try {",
    "  await runOutboxWorker(db, outboxHandlers as Record<string, OutboxHandler>, {",
    "    intervalMs,",
    "    limit,",
    "    maxAttempts,",
    "    retryDelaySeconds,",
    "    requeueStaleAfterSeconds,",
    "    signal: controller.signal,",
    "    onIteration(result) {",
    "      if (result.processed.length > 0 || result.failed.length > 0) {",
    "        console.log(`outbox processed=${result.processed.length} failed=${result.failed.length} retried=${result.retried.length} dead=${result.deadLettered.length}`);",
    "      }",
    "    },",
    "  });",
    "} finally {",
    "  await db.end?.();",
    "}",
    "",
    "void afterCommitHandlers;",
  ];

  return `${lines.join("\n")}\n`;
}

function enumTypes(schema: SchemaIr): string[] {
  return schema.enums.flatMap((enumeration) => [
    `export type ${enumeration.name} = ${enumeration.values.map((value) => quoteString(value)).join(" | ")};`,
    "",
  ]);
}

function entityTypes(schema: SchemaIr): string[] {
  return schema.entities.flatMap((entity) => [
    `export interface ${entity.name}Row {`,
    ...entity.fields.map((field) => `  ${field.columnName}${field.nullable ? "?" : ""}: ${fieldType(schema, field)};`),
    "}",
    "",
  ]);
}

function queryTypes(schema: SchemaIr, queries: QueryDeclaration[]): string[] {
  return queries.flatMap((query) => [
    ...parameterInterface(schema, `${pascalCase(query.name)}Params`, query.parameters),
    `export type ${pascalCase(query.name)}Row = ${queryRowType(schema, query)};`,
    "",
  ]);
}

function transactionTypes(transactions: TransactionDeclaration[], schema?: SchemaIr): string[] {
  return transactions.flatMap((transaction) => parameterInterface(schema, `${pascalCase(transaction.name)}Params`, transaction.parameters));
}

function eventPayloadTypes(schema: SchemaIr): string[] {
  if (schema.events.length === 0) return [];
  return schema.events.flatMap((event) => [
    `export interface ${event.name}Payload {`,
    ...event.fields.map((field) => `  ${field.name}${field.nullable ? "?" : ""}: ${typeRefToTs(field.type, schema)};`),
    "}",
    "",
  ]);
}

function hookTypes(hooks: string[]): string[] {
  return hooks.flatMap((hook) => [
    `type AfterCommitHandlerFor${hook} = (hook: AfterCommitHook & { name: ${quoteString(hook)} }) => Promise<void> | void;`,
    "",
  ]);
}

function outboxHandlerDeclaration(events: string[], schema: SchemaIr): string {
  if (events.length === 0) return "const outboxHandlers = {";
  const fields = events
    .map((event) => {
      const payloadType = schema.events.some((candidate) => candidate.name === event) ? `${event}Payload` : "unknown";
      return `${event}: TypedOutboxHandler<${payloadType}>`;
    })
    .join("; ");
  return `const outboxHandlers: { ${fields} } = {`;
}

function afterCommitHandlerDeclaration(hooks: string[]): string {
  if (hooks.length === 0) return "const afterCommitHandlers = {";
  return `const afterCommitHandlers: { ${hooks.map((hook) => `${hook}: AfterCommitHandlerFor${hook}`).join("; ")} } = {`;
}

function routeHandler(group: "queries" | "transactions", name: string, parameterType: string | undefined): string {
  const body = parameterType ? `body as ${parameterType}` : "";
  return `    ${name}: async (body: unknown) => api.${group}.${name}(${body}),`;
}

function routeParamSpec(schema: SchemaIr, name: string, parameters: { name: string; type: TypeRef }[]): string {
  return `    ${name}: [${parameters.map((parameter) => `{ name: ${quoteString(parameter.name)}, optional: ${parameter.type.optional ? "true" : "false"}, kind: ${quoteString(httpParamKind(schema, parameter.type))} }`).join(", ")}],`;
}

function httpParamKind(schema: SchemaIr, type: TypeRef): "boolean" | "integer" | "number" | "numeric" | "string" | "json" {
  if (type.name === "Bool") return "boolean";
  if (type.name === "Int") return "integer";
  if (type.name === "Float") return "number";
  if (type.name === "Int64" || type.name === "Decimal") return "numeric";
  if (type.name === "Json") return "json";
  if (type.name === "CurrencyCode") return "string";
  if (type.name === "Id" || schema.entities.some((entity) => entity.name === type.name)) return "string";
  if (schema.enums.some((enumeration) => enumeration.name === type.name)) return "string";
  return "string";
}

function enqueueEvents(body: string): string[] {
  return transactionBodyLines(body).flatMap((line) => {
    const match = line.match(/^(?:if\s+.+\s+then\s+)?enqueue\s+([A-Za-z_][A-Za-z0-9_]*)\s+/);
    return match ? [match[1]] : [];
  });
}

function afterCommitHooks(body: string): string[] {
  return transactionBodyLines(body).flatMap((line) => {
    const match = line.match(/^(?:if\s+.+\s+then\s+)?after\s+commit\s+([A-Za-z_][A-Za-z0-9_]*)\(/);
    return match ? [match[1]] : [];
  });
}

function transactionBodyLines(body: string): string[] {
  const lines = body
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const expanded: string[] = [];

  for (let index = 0; index < lines.length; index += 1) {
    const block = lines[index].match(/^if\s+(.+?)\s*\{$/);
    if (!block) {
      expanded.push(lines[index]);
      continue;
    }

    const condition = block[1];
    let closed = false;
    for (index += 1; index < lines.length; index += 1) {
      if (lines[index] === "}") {
        closed = true;
        break;
      }
      expanded.push(`if ${condition} then ${lines[index]}`);
    }
    if (!closed) {
      expanded.push(lines[index - 1] ?? `if ${condition} {`);
    }
  }

  return expanded;
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function parameterInterface(schema: SchemaIr | undefined, name: string, parameters: { name: string; type: TypeRef }[]): string[] {
  if (parameters.length === 0) return [];
  return [
    `export interface ${name} {`,
    ...parameters.map((parameter) => `  ${parameter.name}${parameter.type.optional ? "?" : ""}: ${typeRefToTs(parameter.type, schema)};`),
    "}",
    "",
  ];
}

function apiInterface(apiName: string, queries: QueryDeclaration[], transactions: TransactionDeclaration[]): string[] {
  return [
    `export interface ${apiName} {`,
    "  queries: {",
    ...queries.map(
      (query) =>
        `    ${query.name}(${parameterSignature(query.name, query.parameters)}): Promise<ReuxQueryResult<${pascalCase(query.name)}Row>>;`,
    ),
    "  };",
    "  transactions: {",
    ...transactions.map(
      (transaction) =>
        `    ${transaction.name}(${parameterSignature(transaction.name, transaction.parameters)}): Promise<TransactionRunResult>;`,
    ),
    "  };",
    "}",
    "",
  ];
}

function sqlConstants(schema: SchemaIr, queries: QueryDeclaration[], transactions: TransactionDeclaration[]): string[] {
  return [
    "const querySql = {",
    ...queries.map((query) => `  ${query.name}: ${templateString(queryToPostgres(schema, query))},`),
    "} as const;",
    "",
    "const transactionSql = {",
    ...transactions.map((transaction) => `  ${transaction.name}: ${templateString(transactionToPostgres(schema, transaction))},`),
    "} as const;",
    "",
  ];
}

function apiFactory(
  createName: string,
  apiName: string,
  queries: QueryDeclaration[],
  transactions: TransactionDeclaration[],
): string[] {
  return [
    `export function ${createName}(db: Database): ${apiName} {`,
    "  return {",
    "    queries: {",
    ...queries.map((query) => queryFactoryMethod(query)),
    "    },",
    "    transactions: {",
    ...transactions.map((transaction) => transactionFactoryMethod(transaction)),
    "    },",
    "  };",
    "}",
    "",
  ];
}

function queryFactoryMethod(query: QueryDeclaration): string {
  const params = orderedParams(query.parameters);
  const args = query.parameters.length > 0 ? `params: ${pascalCase(query.name)}Params` : "";
  return [
    `      async ${query.name}(${args}) {`,
    `        return runSqlQuery(db, querySql.${query.name}, ${params}) as Promise<ReuxQueryResult<${pascalCase(query.name)}Row>>;`,
    "      },",
  ].join("\n");
}

function transactionFactoryMethod(transaction: TransactionDeclaration): string {
  const params = orderedParams(transaction.parameters);
  const args = transaction.parameters.length > 0 ? `params: ${pascalCase(transaction.name)}Params` : "";
  const attempts = transaction.retry?.attempts ?? 1;
  return [
    `      async ${transaction.name}(${args}) {`,
    `        return runTransactionSql(db, transactionSql.${transaction.name}, ${params}, ${attempts});`,
    "      },",
  ].join("\n");
}

function orderedParams(parameters: { name: string }[]): string {
  if (parameters.length === 0) return "[]";
  return `[${parameters.map((parameter) => `params.${parameter.name}`).join(", ")}]`;
}

function parameterSignature(name: string, parameters: { name: string; type: TypeRef }[]): string {
  return parameters.length === 0 ? "" : `params: ${pascalCase(name)}Params`;
}

function queryRowType(schema: SchemaIr, query: QueryDeclaration): string {
  const resultType = query.resultType === "Query<infer>" ? inferQueryResultType(schema, query) : query.resultType;
  const record = parseQueryRecord(resultType);
  if (record) {
    return `{ ${[...record.entries()].map(([name, type]) => `${name}: ${sourceTypeToTs(schema, type)}`).join("; ")} }`;
  }

  const entityMatch = resultType.match(/^Query<([A-Za-z_][A-Za-z0-9_]*)>$/);
  const entity = entityMatch ? findEntity(schema, entityMatch[1]) : undefined;
  return entity ? `${entity.name}Row` : "unknown";
}

function parseQueryRecord(resultType: string): Map<string, string> | undefined {
  const match = resultType.match(/^Query<\{(.+)\}>$/);
  if (!match) return undefined;
  const fields = new Map<string, string>();
  for (const part of splitTopLevel(match[1], ",")) {
    const separator = part.indexOf(":");
    if (separator < 0) return undefined;
    fields.set(part.slice(0, separator).trim(), part.slice(separator + 1).trim());
  }
  return fields;
}

function splitTopLevel(source: string, separator: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;
  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    if (char === "<" || char === "{" || char === "(") depth += 1;
    if (char === ">" || char === "}" || char === ")") depth -= 1;
    if (depth === 0 && char === separator) {
      parts.push(source.slice(start, index).trim());
      start = index + 1;
    }
  }
  parts.push(source.slice(start).trim());
  return parts.filter(Boolean);
}

function fieldType(schema: SchemaIr, field: FieldIr): string {
  const value = field.reference ? "string" : sourceTypeNameToTs(field.type.name, field.type.args[0]?.name, schema);
  return field.nullable ? `${value} | null` : value;
}

function typeRefToTs(type: TypeRef, schema?: SchemaIr): string {
  const base = sourceTypeNameToTs(type.name, type.args[0]?.name, schema);
  return type.optional ? `${base} | null` : base;
}

function sourceTypeToTs(schema: SchemaIr, source: string): string {
  return typeRefToTs(parseTypeRef(source), schema);
}

function sourceTypeNameToTs(typeName: string, idArg?: string, schema?: SchemaIr): string {
  if (typeName === "Id") return "string";
  if (schema?.enums.some((enumeration) => enumeration.name === typeName)) return typeName;
  if (schema?.entities.some((entity) => entity.name === typeName)) return "string";
  switch (typeName) {
    case "Bool":
      return "boolean";
    case "Int":
      return "number";
    case "Int64":
      return "number | string";
    case "Float":
    case "Decimal":
      return "number | string";
    case "String":
    case "CurrencyCode":
    case "Bytes":
    case "Duration":
    case "Uuid":
      return "string";
    case "Date":
    case "Time":
    case "Instant":
      return "string | Date";
    case "Json":
      return "unknown";
    default:
      return typeName;
  }
}

function pascalCase(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9]+/g, " ");
  const words = cleaned.match(/[A-Za-z0-9]+/g) ?? ["Reux"];
  return words.map((word) => `${word[0].toUpperCase()}${word.slice(1)}`).join("");
}

function quoteString(value: string): string {
  return JSON.stringify(value);
}

function templateString(value: string): string {
  return `\`${value.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${")}\``;
}
