import { parseProgram } from "./parser.js";
import { buildSimulationCatalog, runSimulationIr, SimulationIr, SimulationRunResult } from "./simulation-ir.js";

export function emitTypeScriptSimulationContracts(source: string): string {
  const simulations = buildSimulationCatalog(parseProgram(source));
  const lines = [
    "// Generated by Reux. Do not edit by hand.",
    "",
    "export type ReuxSimulationValue = boolean | number | string;",
    "",
    "export interface ReuxSimulationAssumptionDelta<Value = ReuxSimulationValue> {",
    "  name: string;",
    "  baseline: Value;",
    "  previous: Value;",
    "  current: Value;",
    "  changedFromPrevious: boolean;",
    "  changedFromBaseline: boolean;",
    "  deltaFromPrevious?: number;",
    "  deltaFromBaseline?: number;",
    "  unit?: string;",
    "}",
    "",
    "export interface ReuxSimulationValueSeriesPoint<Value = ReuxSimulationValue> {",
    "  period: number;",
    "  label: string;",
    "  value: Value;",
    "  changedFromPrevious: boolean;",
    "  changedFromBaseline: boolean;",
    "  deltaFromPrevious?: number;",
    "  deltaFromBaseline?: number;",
    "}",
    "",
    "export interface ReuxSimulationNumberSeriesPoint {",
    "  period: number;",
    "  label: string;",
    "  value: number;",
    "}",
    "",
    "export interface ReuxSimulationAssumptionSeries<Assumptions extends object> {",
    "  name: keyof Assumptions;",
    "  unit?: string;",
    "  points: Array<ReuxSimulationValueSeriesPoint<Assumptions[keyof Assumptions]>>;",
    "}",
    "",
    "export interface ReuxSimulationMetricSeries<Metrics extends object> {",
    "  name: keyof Metrics;",
    "  unit?: string;",
    "  points: ReuxSimulationNumberSeriesPoint[];",
    "}",
    "",
    "export interface ReuxSimulationTimeSeries<Assumptions extends object, Metrics extends object> {",
    "  assumptions: Array<ReuxSimulationAssumptionSeries<Assumptions>>;",
    "  metrics: Array<ReuxSimulationMetricSeries<Metrics>>;",
    "}",
    "",
    "export interface ReuxSimulationObjective<MetricName extends string = string> {",
    "  metric: MetricName;",
    "  direction: \"maximize\" | \"minimize\";",
    "}",
    "",
    "export interface ReuxSimulationForecast {",
    "  periods: number;",
    "  unit: \"day\" | \"week\" | \"month\" | \"quarter\" | \"year\";",
    "}",
    "",
    "export interface ReuxSimulationDimension {",
    "  name: string;",
    "  value: string;",
    "}",
    "",
    "export interface ReuxSimulationPeriod<Assumptions extends object, Metrics extends object> {",
    "  period: number;",
    "  label: string;",
    "  assumptions: Assumptions;",
    "  assumptionUnits: Partial<Record<keyof Assumptions, string>>;",
    "  assumptionDeltas: Partial<{ [Name in keyof Assumptions]: ReuxSimulationAssumptionDelta<Assumptions[Name]> }>;",
    "  appliedChanges: Array<{ period: number; unit: ReuxSimulationForecast[\"unit\"] }>;",
    "  metrics: Metrics;",
    "  metricUnits: Partial<Record<keyof Metrics, string>>;",
    "}",
    "",
    "export interface ReuxSimulationScenarioRun<ScenarioName extends string, Assumptions extends object, Metrics extends object> {",
    "  name: ScenarioName;",
    "  periods: Array<ReuxSimulationPeriod<Assumptions, Metrics>>;",
    "  timeSeries: ReuxSimulationTimeSeries<Assumptions, Metrics>;",
    "}",
    "",
    "export interface ReuxSimulationPeriodDelta<Metrics extends object> {",
    "  period: number;",
    "  label: string;",
    "  metricDeltas: Metrics;",
    "  metricUnits: Partial<Record<keyof Metrics, string>>;",
    "}",
    "",
    "export interface ReuxSimulationMetricRanking<ScenarioName extends string, MetricName extends string> {",
    "  metric: MetricName;",
    "  unit?: string;",
    "  objective?: \"maximize\" | \"minimize\";",
    "  direction: \"descending_delta\" | \"ascending_delta\";",
    "  scenarios: Array<{ name: ScenarioName; delta: number; rank: number }>;",
    "}",
    "",
    "export interface ReuxSimulationExplanation<ScenarioName extends string, MetricName extends string> {",
    "  metric: MetricName;",
    "  unit?: string;",
    "  objective?: \"maximize\" | \"minimize\";",
    "  preferredScenario?: ScenarioName;",
    "  preferredDelta?: number;",
    "  firstDivergence?: { scenario: ScenarioName; period: number; label: string };",
    "  summary: string;",
    "}",
    "",
    "export interface ReuxSimulationMetricSummary<ScenarioName extends string, MetricName extends string> {",
    "  metric: MetricName;",
    "  unit?: string;",
    "  objective?: \"maximize\" | \"minimize\";",
    "  preferredScenario?: ScenarioName;",
    "  preferredDelta?: number;",
    "  formattedDelta: string;",
    "  firstDivergence?: { scenario: ScenarioName; period: number; label: string };",
    "  summary: string;",
    "}",
    "",
    "export interface ReuxSimulationScenarioMetricDelta<MetricName extends string> {",
    "  metric: MetricName;",
    "  delta: number;",
    "  unit?: string;",
    "  formattedDelta: string;",
    "}",
    "",
    "export interface ReuxSimulationComparison<ScenarioName extends string, Metrics extends object, MetricName extends string> {",
    "  baseline: \"baseline\";",
    "  finalPeriod: number;",
    "  scenarios: Array<{",
    "    name: Exclude<ScenarioName, \"baseline\">;",
    "    metricDeltas: Metrics;",
    "    metricUnits: Partial<Record<keyof Metrics, string>>;",
    "    firstDivergence?: ReuxSimulationPeriodDelta<Metrics>;",
    "    periodDeltas: Array<ReuxSimulationPeriodDelta<Metrics>>;",
    "  }>;",
    "  metricRankings: Array<ReuxSimulationMetricRanking<Exclude<ScenarioName, \"baseline\">, MetricName>>;",
    "  explanations: Array<ReuxSimulationExplanation<Exclude<ScenarioName, \"baseline\">, MetricName>>;",
    "}",
    "",
    "export interface ReuxSimulationRun<SimulationName extends string, ScenarioName extends string, Assumptions extends object, Metrics extends object, MetricName extends string> {",
    "  name: SimulationName;",
    "  model: \"prototype-formula-forecast\";",
    "  dimensions: Record<string, string>;",
    "  forecast: ReuxSimulationForecast;",
    "  objectives: Array<ReuxSimulationObjective<MetricName>>;",
    "  periods: Array<ReuxSimulationPeriod<Assumptions, Metrics>>;",
    "  timeSeries: ReuxSimulationTimeSeries<Assumptions, Metrics>;",
    "  scenarios?: Array<ReuxSimulationScenarioRun<ScenarioName, Assumptions, Metrics>>;",
    "  comparison?: ReuxSimulationComparison<ScenarioName, Metrics, MetricName>;",
    "}",
    "",
    "export interface ReuxSimulationMetadata {",
    "  name: string;",
    "  dimensions: readonly ReuxSimulationDimension[];",
    "  forecast: ReuxSimulationForecast;",
    "  assumptions: readonly { name: string; type: \"boolean\" | \"number\" | \"string\"; unit?: string }[];",
    "  metrics: readonly string[];",
    "  objectives: readonly ReuxSimulationObjective[];",
    "  scenarios: readonly string[];",
    "}",
    "",
    "export function formatReuxSimulationDelta(delta: number | undefined, unit?: string): string {",
    "  if (delta === undefined) return \"-\";",
    "  const value = Number(delta.toFixed(6));",
    "  return unit ? `${value} ${unit}` : String(value);",
    "}",
    "",
    "export function findReuxSimulationRanking<ScenarioName extends string, Metrics extends object, MetricName extends string>(",
    "  comparison: ReuxSimulationComparison<ScenarioName, Metrics, MetricName>,",
    "  metric: MetricName,",
    "): ReuxSimulationMetricRanking<Exclude<ScenarioName, \"baseline\">, MetricName> | undefined {",
    "  return comparison.metricRankings.find((ranking) => ranking.metric === metric);",
    "}",
    "",
    "export function findReuxSimulationExplanation<ScenarioName extends string, Metrics extends object, MetricName extends string>(",
    "  comparison: ReuxSimulationComparison<ScenarioName, Metrics, MetricName>,",
    "  metric: MetricName,",
    "): ReuxSimulationExplanation<Exclude<ScenarioName, \"baseline\">, MetricName> | undefined {",
    "  return comparison.explanations.find((explanation) => explanation.metric === metric);",
    "}",
    "",
    "export function summarizeReuxSimulationComparison<ScenarioName extends string, Metrics extends object, MetricName extends string>(",
    "  comparison: ReuxSimulationComparison<ScenarioName, Metrics, MetricName>,",
    "): Array<ReuxSimulationMetricSummary<Exclude<ScenarioName, \"baseline\">, MetricName>> {",
    "  return comparison.metricRankings.map((ranking) => {",
    "    const explanation = findReuxSimulationExplanation(comparison, ranking.metric);",
    "    const preferred = ranking.scenarios[0];",
    "    return {",
    "      metric: ranking.metric,",
    "      unit: ranking.unit,",
    "      objective: ranking.objective,",
    "      preferredScenario: explanation?.preferredScenario ?? preferred?.name,",
    "      preferredDelta: explanation?.preferredDelta ?? preferred?.delta,",
    "      formattedDelta: formatReuxSimulationDelta(explanation?.preferredDelta ?? preferred?.delta, ranking.unit),",
    "      firstDivergence: explanation?.firstDivergence,",
    "      summary: explanation?.summary ?? `No explanation was emitted for ${ranking.metric}.`,",
    "    };",
    "  });",
    "}",
    "",
    "export function listReuxSimulationScenarioDeltas<ScenarioName extends string, Metrics extends object, MetricName extends string>(",
    "  comparison: ReuxSimulationComparison<ScenarioName, Metrics, MetricName>,",
    "  scenarioName: Exclude<ScenarioName, \"baseline\">,",
    "): Array<ReuxSimulationScenarioMetricDelta<MetricName>> {",
    "  const scenario = comparison.scenarios.find((candidate) => candidate.name === scenarioName);",
    "  if (!scenario) return [];",
    "  return Object.entries(scenario.metricDeltas as Record<string, number>).map(([metric, delta]) => {",
    "    const metricName = metric as MetricName;",
    "    const unit = scenario.metricUnits[metric as keyof Metrics];",
    "    return {",
    "      metric: metricName,",
    "      delta,",
    "      unit,",
    "      formattedDelta: formatReuxSimulationDelta(delta, unit),",
    "    };",
    "  });",
    "}",
    "",
    ...simulations.flatMap((simulation) => simulationContractLines(simulation)),
    `export const reuxSimulationCatalog = [${simulations.map((simulation) => `${camelCase(simulation.name)}Simulation`).join(", ")}] as const;`,
    "",
    "export type ReuxGeneratedSimulationMetadata = typeof reuxSimulationCatalog[number];",
    "",
    "export function listReuxSimulationNames(): Array<ReuxGeneratedSimulationMetadata[\"name\"]> {",
    "  return reuxSimulationCatalog.map((simulation) => simulation.name);",
    "}",
    "",
    "export function findReuxSimulationMetadata(name: string): ReuxGeneratedSimulationMetadata | undefined {",
    "  return reuxSimulationCatalog.find((simulation) => simulation.name === name);",
    "}",
  ];

  return `${lines.join("\n")}\n`;
}

function simulationContractLines(simulation: SimulationIr): string[] {
  const run = runSimulationIr(simulation);
  const typeName = pascalCase(simulation.name);
  const assumptions = simulation.assumptions.map((assumption) => assumption.name);
  const metrics = metricNames(run);
  const scenarios = run.scenarios?.map((scenario) => scenario.name) ?? ["baseline"];

  return [
    `export type ${typeName}SimulationName = ${quoteString(simulation.name)};`,
    `export type ${typeName}DimensionName = ${stringUnion(simulation.dimensions.map((dimension) => dimension.name))};`,
    `export type ${typeName}AssumptionName = ${stringUnion(assumptions)};`,
    `export type ${typeName}MetricName = ${stringUnion(metrics)};`,
    `export type ${typeName}ScenarioName = ${stringUnion(scenarios)};`,
    "",
    `export interface ${typeName}Assumptions {`,
    ...simulation.assumptions.map((assumption) => `  ${assumption.name}: ${assumptionType(assumption.type)};`),
    "}",
    "",
    `export interface ${typeName}Metrics {`,
    ...metrics.map((metric) => `  ${metric}: number;`),
    "}",
    "",
    `export type ${typeName}Run = ReuxSimulationRun<${typeName}SimulationName, ${typeName}ScenarioName, ${typeName}Assumptions, ${typeName}Metrics, ${typeName}MetricName>;`,
    "",
    `export const ${camelCase(simulation.name)}Simulation = ${JSON.stringify(simulationMetadata(simulation, run), null, 2)} as const satisfies ReuxSimulationMetadata;`,
    "",
  ];
}

function simulationMetadata(simulation: SimulationIr, run: SimulationRunResult): unknown {
  return {
    name: simulation.name,
    dimensions: simulation.dimensions,
    forecast: simulation.forecast,
    assumptions: simulation.assumptions.map((assumption) => ({
      name: assumption.name,
      type: assumption.type,
      unit: assumption.unit,
    })),
    metrics: metricNames(run),
    objectives: simulation.objectives,
    scenarios: run.scenarios?.map((scenario) => scenario.name) ?? ["baseline"],
  };
}

function metricNames(run: SimulationRunResult): string[] {
  const names = new Set<string>();
  for (const period of run.periods) {
    for (const metric of Object.keys(period.metrics)) names.add(metric);
  }
  for (const scenario of run.scenarios ?? []) {
    for (const period of scenario.periods) {
      for (const metric of Object.keys(period.metrics)) names.add(metric);
    }
  }
  return [...names].sort();
}

function assumptionType(type: SimulationIr["assumptions"][number]["type"]): string {
  if (type === "boolean") return "boolean";
  if (type === "number") return "number";
  return "string";
}

function stringUnion(values: string[]): string {
  return values.length > 0 ? values.map(quoteString).join(" | ") : "never";
}

function pascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? ["Reux"];
  return words.map((word) => `${word[0].toUpperCase()}${word.slice(1)}`).join("");
}

function camelCase(value: string): string {
  const pascal = pascalCase(value);
  return `${pascal[0].toLowerCase()}${pascal.slice(1)}`;
}

function quoteString(value: string): string {
  return JSON.stringify(value);
}
