import { parseProgram } from "./parser.js";
import { buildSimulationCatalog, runSimulationIr, SimulationIr, SimulationRunResult } from "./simulation-ir.js";

export function emitTypeScriptSimulationContracts(source: string): string {
  const simulations = buildSimulationCatalog(parseProgram(source));
  const lines = [
    "// Generated by Reux. Do not edit by hand.",
    "",
    "export type ReuxSimulationValue = boolean | number | string;",
    "",
    "export interface ReuxSimulationObjective<MetricName extends string = string> {",
    "  metric: MetricName;",
    "  direction: \"maximize\" | \"minimize\";",
    "}",
    "",
    "export interface ReuxSimulationForecast {",
    "  periods: number;",
    "  unit: \"day\" | \"week\" | \"month\" | \"quarter\" | \"year\";",
    "}",
    "",
    "export interface ReuxSimulationPeriod<Assumptions extends object, Metrics extends object> {",
    "  period: number;",
    "  label: string;",
    "  assumptions: Assumptions;",
    "  assumptionUnits: Partial<Record<keyof Assumptions, string>>;",
    "  appliedChanges: Array<{ period: number; unit: ReuxSimulationForecast[\"unit\"] }>;",
    "  metrics: Metrics;",
    "  metricUnits: Partial<Record<keyof Metrics, string>>;",
    "}",
    "",
    "export interface ReuxSimulationScenarioRun<ScenarioName extends string, Assumptions extends object, Metrics extends object> {",
    "  name: ScenarioName;",
    "  periods: Array<ReuxSimulationPeriod<Assumptions, Metrics>>;",
    "}",
    "",
    "export interface ReuxSimulationPeriodDelta<Metrics extends object> {",
    "  period: number;",
    "  label: string;",
    "  metricDeltas: Metrics;",
    "  metricUnits: Partial<Record<keyof Metrics, string>>;",
    "}",
    "",
    "export interface ReuxSimulationMetricRanking<ScenarioName extends string, MetricName extends string> {",
    "  metric: MetricName;",
    "  unit?: string;",
    "  objective?: \"maximize\" | \"minimize\";",
    "  direction: \"descending_delta\" | \"ascending_delta\";",
    "  scenarios: Array<{ name: ScenarioName; delta: number; rank: number }>;",
    "}",
    "",
    "export interface ReuxSimulationExplanation<ScenarioName extends string, MetricName extends string> {",
    "  metric: MetricName;",
    "  unit?: string;",
    "  objective?: \"maximize\" | \"minimize\";",
    "  preferredScenario?: ScenarioName;",
    "  preferredDelta?: number;",
    "  firstDivergence?: { scenario: ScenarioName; period: number; label: string };",
    "  summary: string;",
    "}",
    "",
    "export interface ReuxSimulationComparison<ScenarioName extends string, Metrics extends object, MetricName extends string> {",
    "  baseline: \"baseline\";",
    "  finalPeriod: number;",
    "  scenarios: Array<{",
    "    name: Exclude<ScenarioName, \"baseline\">;",
    "    metricDeltas: Metrics;",
    "    metricUnits: Partial<Record<keyof Metrics, string>>;",
    "    firstDivergence?: ReuxSimulationPeriodDelta<Metrics>;",
    "    periodDeltas: Array<ReuxSimulationPeriodDelta<Metrics>>;",
    "  }>;",
    "  metricRankings: Array<ReuxSimulationMetricRanking<Exclude<ScenarioName, \"baseline\">, MetricName>>;",
    "  explanations: Array<ReuxSimulationExplanation<Exclude<ScenarioName, \"baseline\">, MetricName>>;",
    "}",
    "",
    "export interface ReuxSimulationRun<SimulationName extends string, ScenarioName extends string, Assumptions extends object, Metrics extends object, MetricName extends string> {",
    "  name: SimulationName;",
    "  model: \"prototype-formula-forecast\";",
    "  forecast: ReuxSimulationForecast;",
    "  objectives: Array<ReuxSimulationObjective<MetricName>>;",
    "  periods: Array<ReuxSimulationPeriod<Assumptions, Metrics>>;",
    "  scenarios?: Array<ReuxSimulationScenarioRun<ScenarioName, Assumptions, Metrics>>;",
    "  comparison?: ReuxSimulationComparison<ScenarioName, Metrics, MetricName>;",
    "}",
    "",
    ...simulations.flatMap((simulation) => simulationContractLines(simulation)),
  ];

  return `${lines.join("\n")}\n`;
}

function simulationContractLines(simulation: SimulationIr): string[] {
  const run = runSimulationIr(simulation);
  const typeName = pascalCase(simulation.name);
  const assumptions = simulation.assumptions.map((assumption) => assumption.name);
  const metrics = metricNames(run);
  const scenarios = run.scenarios?.map((scenario) => scenario.name) ?? ["baseline"];

  return [
    `export type ${typeName}SimulationName = ${quoteString(simulation.name)};`,
    `export type ${typeName}AssumptionName = ${stringUnion(assumptions)};`,
    `export type ${typeName}MetricName = ${stringUnion(metrics)};`,
    `export type ${typeName}ScenarioName = ${stringUnion(scenarios)};`,
    "",
    `export interface ${typeName}Assumptions {`,
    ...simulation.assumptions.map((assumption) => `  ${assumption.name}: ${assumptionType(assumption.type)};`),
    "}",
    "",
    `export interface ${typeName}Metrics {`,
    ...metrics.map((metric) => `  ${metric}: number;`),
    "}",
    "",
    `export type ${typeName}Run = ReuxSimulationRun<${typeName}SimulationName, ${typeName}ScenarioName, ${typeName}Assumptions, ${typeName}Metrics, ${typeName}MetricName>;`,
    "",
    `export const ${camelCase(simulation.name)}Simulation = ${JSON.stringify(simulationMetadata(simulation, run), null, 2)} as const;`,
    "",
  ];
}

function simulationMetadata(simulation: SimulationIr, run: SimulationRunResult): unknown {
  return {
    name: simulation.name,
    forecast: simulation.forecast,
    assumptions: simulation.assumptions.map((assumption) => ({
      name: assumption.name,
      type: assumption.type,
      unit: assumption.unit,
    })),
    metrics: metricNames(run),
    objectives: simulation.objectives,
    scenarios: run.scenarios?.map((scenario) => scenario.name) ?? ["baseline"],
  };
}

function metricNames(run: SimulationRunResult): string[] {
  const names = new Set<string>();
  for (const period of run.periods) {
    for (const metric of Object.keys(period.metrics)) names.add(metric);
  }
  for (const scenario of run.scenarios ?? []) {
    for (const period of scenario.periods) {
      for (const metric of Object.keys(period.metrics)) names.add(metric);
    }
  }
  return [...names].sort();
}

function assumptionType(type: SimulationIr["assumptions"][number]["type"]): string {
  if (type === "boolean") return "boolean";
  if (type === "number") return "number";
  return "string";
}

function stringUnion(values: string[]): string {
  return values.length > 0 ? values.map(quoteString).join(" | ") : "never";
}

function pascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? ["Reux"];
  return words.map((word) => `${word[0].toUpperCase()}${word.slice(1)}`).join("");
}

function camelCase(value: string): string {
  const pascal = pascalCase(value);
  return `${pascal[0].toLowerCase()}${pascal.slice(1)}`;
}

function quoteString(value: string): string {
  return JSON.stringify(value);
}
